"""empty message

Revision ID: 5b7738a07b98
Revises: c036f781ac83
Create Date: 2024-07-02 17:37:22.834321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7738a07b98'
down_revision: Union[str, None] = 'c036f781ac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'modify_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'modify_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
